// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLBt5HmtHcivAW_WEEV6FATtMLpcKEegA',
    appId: '1:456669389334:android:3500f0232c1da2282e8b37',
    messagingSenderId: '456669389334',
    projectId: 'fife-flutter',
    storageBucket: 'fife-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9N7tWR5ogr0LkKGSapRMWE9C2I_ICkOc',
    appId: '1:456669389334:ios:2f222dd6e69887942e8b37',
    messagingSenderId: '456669389334',
    projectId: 'fife-flutter',
    storageBucket: 'fife-flutter.firebasestorage.app',
    iosBundleId: 'com.jeerovan.fife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9N7tWR5ogr0LkKGSapRMWE9C2I_ICkOc',
    appId: '1:456669389334:ios:2f222dd6e69887942e8b37',
    messagingSenderId: '456669389334',
    projectId: 'fife-flutter',
    storageBucket: 'fife-flutter.firebasestorage.app',
    iosBundleId: 'com.jeerovan.fife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC72wLfQPCB2E0XawejCzI2uI3XGqAzfEs',
    appId: '1:456669389334:web:e7b7216dab0530ce2e8b37',
    messagingSenderId: '456669389334',
    projectId: 'fife-flutter',
    authDomain: 'fife-flutter.firebaseapp.com',
    storageBucket: 'fife-flutter.firebasestorage.app',
  );
}
